name: .NET Core build-test-and-deploy poi

on:
  push:
    branches: [ master ]
    paths: 
    - 'apis/poi/**'
    - '.github/workflows/dotnet-core.yml'
  pull_request:
    branches: [ master ]
    paths: 
    - 'apis/poi/**'
    - '.github/workflows/dotnet-core.yml'

env:
  POI_PATH: './apis/poi/web'

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore './apis/poi/web'
    - name: Build
      run: dotnet build './apis/poi/web' --configuration Release
    - name: Test
      run: dotnet test './apis/poi/tests/UnitTests' --no-restore
    - name: Publish
      run: dotnet publish './apis/poi/web' -c Release -o '${{env.POI_PATH}}/output'
  job2:
    runs-on: ubuntu-latest
    needs: job1
    
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: openhackjqh6rwn6acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build ./apis/poi/web/ -t openhackjqh6rwn6acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
        docker push openhackjqh6rwn6acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackjqh6rwn6poi'
        slot-name: 'staging'
        images: 'openhackjqh6rwn6acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
        
  job3:
    runs-on: ubuntu-latest
    needs: job2
    
    steps:
    - name: Sleep
      run: sleep 180

    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: https://openhackjqh6rwn6userjava-staging.azurewebsites.net/api/healthcheck/user-java
        max-attempts: 30
        retry-delay: 10s
