name: TRIPS

on:
  push:
    branches: [ master ]
    paths: 
    - 'apis/trips/**'
    - '.github/workflows/trips.yml'
  pull_request:
    branches: [ master ]
    paths: 
    - 'apis/trips/**'
    - '.github/workflows/trips.yml'

env:
  TRIPS_PATH: './apis/trips'

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore './apis/trips'
    - name: Build
      run: dotnet build './apis/trips' --configuration Release
    - name: Test
      run: dotnet test './apis/trips/tests/UnitTests' --no-restore
    - name: Publish
      run: dotnet publish './apis/trips' -c Release -o '${{env.TRIPS_PATH}}/output'
  job2:
    runs-on: ubuntu-latest
    needs: job1
    
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: openhackjqh6rwn6acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build ./apis/trips/ -t openhackjqh6rwn6acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}
        docker push openhackjqh6rwn6acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackjqh6rwn6trips'
        images: 'openhackjqh6rwn6acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout

