name: user-java

on:
  push:
    # branches: [ master ]
    branches: '**'
    paths:
    - 'apis/user-java/**'
    - '.github/workflows/user-java.yml'
  pull_request:
    # branches: [ master ]
    branches: '**'
    paths:
    - 'apis/user-java/**'
    - '.github/workflows/user-java.yml'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Maven package
      run: |
        echo "(Dummy message) maven package"

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    # if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@master
    
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: openhackjqh6rwn6acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build ./apis/user-java/ -t openhackjqh6rwn6acr.azurecr.io/devopsoh/api-user-java:${{ github.sha }}
        docker push openhackjqh6rwn6acr.azurecr.io/devopsoh/api-user-java:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackjqh6rwn6userjava'
        slot-name: staging
        images: 'openhackjqh6rwn6acr.azurecr.io/devopsoh/api-user-java:${{ github.sha }}'

    - name: Azure logout
      run: |
        az logout

  job3:
    runs-on: ubuntu-latest
    needs: [job2]

    steps:
    - name: Sleep for checking
      run: sleep 180

    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: https://openhackjqh6rwn6userjava-staging.azurewebsites.net/api/healthcheck/user-java
        max-attempts: 30
        retry-delay: 10s
