name: user-java

on:
  push:
    branches: '**'
    paths:
    - 'apis/user-java/**'
    - '.github/workflows/user-java.yml'
  pull_request:
    branches: '**'
    paths:
    - 'apis/user-java/**'
    - '.github/workflows/user-java.yml'

jobs:
  user-java-maven-package:
    runs-on: ubuntu-latest
    steps:
    - name: Maven package
      run: |
        echo "(Dummy message) maven package"

  user-java-docker-build-push-webapps-deploy:
    runs-on: ubuntu-latest
    needs: [user-java-maven-package]
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@master
    
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: openhackjqh6rwn6acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build ./apis/user-java/ -t openhackjqh6rwn6acr.azurecr.io/devopsoh/api-user-java:${{ github.sha }}
        docker push openhackjqh6rwn6acr.azurecr.io/devopsoh/api-user-java:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackjqh6rwn6userjava'
        images: 'openhackjqh6rwn6acr.azurecr.io/devopsoh/api-user-java:${{ github.sha }}'

    - name: Azure logout
      run: |
        az logout
